In [1]:
# import packages
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
# define example data
pred = np.array(['Agri', 'Agri', 'Forest', 'Forest', 'Forest', 'Water', 'Water', 'Forest', 'Forest', 'Forest', 'Agri', 'Agri', 'Forest', 'Forest', 'Agri'])
true = np.array(['Agri', 'Forest', 'Forest', 'Forest', 'Water', 'Water', 'Forest', 'Agri', 'Agri', 'Forest', 'Agri', 'Agri', 'Forest', 'Agri', 'Agri'])

In [2]:
# print the confusion matrix
print(confusion_matrix(true, pred))

[[4 3 0]
 [1 4 1]
 [0 1 1]]


In [3]:
# compute overall accuracy
accuracy_score(true, pred)

0.6

In [4]:
# compute Kappa
cohen_kappa_score(true, pred)

0.34782608695652173

In [5]:
# compute F1-scores
f1_score(true, pred, average=None)# compute F1-scores

array([0.66666667, 0.57142857, 0.5       ])

In [6]:
# summary of all metrics
print(classification_report(true, pred))

              precision    recall  f1-score   support

        Agri       0.80      0.57      0.67         7
      Forest       0.50      0.67      0.57         6
       Water       0.50      0.50      0.50         2

    accuracy                           0.60        15
   macro avg       0.60      0.58      0.58        15
weighted avg       0.64      0.60      0.61        15

